#!/usr/bin/env bash
source src/modules_functions

function print_help()
{
	echo "print ussage"
}

# check if valid mode
case $1 in
		add|init|remove)  
				mode=$1
				shift
				;;
		*) print_help
				;;
esac

# check if module option set
module_opt=0
case $1 in
		-m)  
				module_opt=1
				shift
				module_name=$1
				shift
				;;
esac


# there can be no additional arguments
if [ $# -gt 0 ];then
	print_help
	exit
fi

# if module_opt set than module name must be set
if [ $module_opt -eq 1 ] && [ "$module_name" = "" ];then
	print_help
	exit
fi

case $mode in
		init)  
			if [ $module_opt -eq 1 ];then
				init_module $module_name
			else 
				init_modules
			fi
			;;
		add)  
			if [ $module_opt -eq 1 ];then
				process_module $module_name
			else 
				process_modules
			fi
			;;
		remove) echo "not supported yet" 
			;;
esac

