#!/usr/bin/env bash
source src/modules_functions

function print_help()
{
	printf "
NAME
     confiles -- add or remove modules for confiles

SYNOPSIS
     confiles [OPTION] [-m] [module-name]

DESCRIPTION
    Dotfiles will init, add or remove module. For additional info check README.md
     
     The OPTION are as follows:
     - add
     - remove
     - init_module

     Additional option:
     -m module-name  Runs for induvidual modules
"
}


function print_usage()
{
	printf "
Usage: confiles [OPTION] [-m] [module-name]
Try confiles --help for more options.
"
}


mode=$1
shift

# check if module option set
module_opt=0
case $1 in
	 -m)  
		module_opt=1
		shift
		module_name=$1
		if [ "$module_name" = "" ];then
			echo "Missing module name"
			print_usage
			exit
		fi
		shift
		;;
esac

# there can be no additional arguments
if [ $# -gt 0 ];then	
	echo "To many arguments"
	print_usage
	exit
fi


case $mode in
		init)  
			if [ $module_opt -eq 1 ];then
				init_module $module_name
			else 
				init_modules
			fi
			;;
		add)  
			if [ $module_opt -eq 1 ];then
				add_module $module_name
			else 
				add_modules
			fi
			;;
		remove) 
			if [ $module_opt -eq 1 ];then
				remove_module $module_name
			else 
				remove_modules
			fi
			;;
		*)
			print_usage
			exit
			;;
esac

