#!/usr/bin/env bash

# ==============================================================================
# Additional application config
# ==============================================================================


# ==============================================================================
# MPV
# ==============================================================================

mpv_conf=$HOME/.config/mpv/mpv.conf;
mpv_input_conf=$HOME/.config/mpv/input.conf;

echo "ass-style-override=force" >> $mpv_conf
echo "sub-text-font='Helvetica'" >> $mpv_conf
echo "sub-text-bold=yes" >> $mpv_conf
echo "sub-text-font-size=55" >> $mpv_conf
echo "sub-text-border-size=4" >> $mpv_conf
echo "sub-scale-by-window=no" >> $mpv_conf
echo "sub-use-margins=no" >> $mpv_conf
echo "osd-font='Helvetica'" >> $mpv_conf
echo "osd-bold=yes" >> $mpv_conf
echo "osd-font-size=55" >> $mpv_conf
echo "osd-border-size=4" >> $mpv_conf
echo "osd-scale-by-window=no" >> $mpv_conf

echo "< add sub-scale -0.1" >> $mpv_input_conf
echo "> add sub-scale +0.1" >> $mpv_input_conf

# ==============================================================================
# Transmission
# ==============================================================================

# Hide the donate message
defaults write org.m0k.transmission WarningDonate -bool false

# Hide the legal disclaimer
defaults write org.m0k.transmission WarningLegal -bool false

# IP block list.
# Source: https://giuliomac.wordpress.com/2014/02/19/best-blocklist-for-transmission/
defaults write org.m0k.transmission BlocklistNew -bool true
defaults write org.m0k.transmission BlocklistURL -string "http://john.bitsurge.net/public/biglist.p2p.gz"
defaults write org.m0k.transmission BlocklistAutoUpdate -bool true


# Kill affected applications
for app in "Transmission" "mpv";
do
	killall "$app" > /dev/null 2>&1
done
echo "Done. Note that some of these changes require a logout/restart to take effect."
