#!/usr/bin/env bash

# application directory
APP_DIR="$(pwd)"

# config stub file path
CONFIG_STUB_PATH="$APP_DIR/stubs/config"

# config file destination path
CONFIG_PATH="$APP_DIR/config"

# info files path
INFO_PATH="$APP_DIR/info"

# modules folder path
MODULES_PATH="$APP_DIR/modules"

# operations
OP_ADD="add"
OP_REMOVE="remove"
