#!/usr/bin/env bash

# 
APP_DIR="$(cd ..; pwd)"


# config stub file path
CONFIG_STUB_PATH="$APP_DIR/stubs/config/config"

# config file destination path
CONFIG_PATH="$APP_DIR/config"

# modules folder path
MODULES_PATH="$APP_DIR/stubs/modules"

