#!/usr/bin/env bash

# args
# $1 - needle
# $2 - haystack
function in_array()
{
	local hay needle=$1
	shift
	for hay in $@;
	do
		if [ "$hay" = "$needle" ];then
			return 0
		fi
	done
	return 1
}


# add file - copy or make symbolic links
#
# args:
# $1 - source directory
# $2 - destination directory
# $3 - file name
# $4 - mode (copy or link)
function add_file()
{
	local source_dir=$1
	local destination_dir=$2
	local filename=$3
	local mode=$4


	# create destination directory if it doesn't exist
	if ! [ -d $destination_dir ];then
		mkdir -p $destination_dir
	fi

	# if the destination file exists delete it
	if [ -e $destination_dir/$filename ];then
		rm $destination_dir/$filename
	fi

	# copy file or create a symbolic link
	if [ $mode = "copy" ];then
			ditto -v $source_dir/$filename $destination_dir/$filename
	elif [ $mode = "link" ]; then
			ln -sfhv $source_dir/$filename $destination_dir/$filename
	fi
}

# removes file
#
# args:
# $1 - source directory
# $2 - file name
function remove_file()
{
	local destination_dir=$1
	local filename=$2
	rm -v $destination_dir/$filename
}



# process directory and copy/link folders/files
#
# args
# $1 - source directory
# $2 - destination directory
# $3 - mode (link or copy)
# $4 - operation (add or remove)
# $5 .. - ignore files
function process_directory()
{

	local source_dir=$1
	local destination_dir=$2
	local mode=$3
	local operation=$4
	shift 4
	local ignore=$@	
	
	shopt -s dotglob
	# iterate and process all files/directories in source $1 
	for f in $source_dir/*;
	do
		current_file=$(basename $f)
		# if file is in ingore list skip it
		if in_array "$current_file" "${ignore[@]}";then
			continue
		fi

		if [ -d $source_dir/$current_file ];then
			process_directory $source_dir/$current_file $destination_dir/$current_file $mode $operation "${ignore[@]}"
		else 
			if [ $operation = $OP_ADD ];then
				add_file $source_dir $destination_dir $current_file $mode
			else
				remove_file $destination_dir $current_file
			fi
		fi
	done
}